apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | int }} 
      targetPort: 3000
