name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

  deploy:
    name: Deploy no Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Atualizar deployment no Kubernetes
        run: |
          kubectl set image deployment/hello-app hello-world=${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest
